### ISSUE TITLE
X-Y-Diagrams

### ISSUE THREAD

**Issue by syxolk** [tum-rt/web-quiz#9]
How x-y diagrams could look like in YAML:

```yaml
- xy_diagram:
    title: How fast is my car?
    x_axis:
      label: Time t in seconds
      type: linear # logarithmic
    y_axis:
      label: Location s in m
    lines:
    - label: car
      x: [0, 1, 2, 3]
      y: [0, 0.5, 3, 10]
    markers:
    - label: Estimation
      x: 4
      y: 20
```
